services:
  postgres:
    image: postgres:18.3
    container_name: notes-stack-postgres
    restart: unless-stopped
    env_file:
      - ../../env/postgres.env.example
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
